Setting Z3, Boogie, and Corral to appropriate versions.
Boogie also moved to github recently. So mercurial is no longer a dependency
for us, which is nice.
Unfortunately, there is an issue with cloning Boogie. For some reason I keep
getting this weird error:
error: rpc failed; result=56, http code = 200